Repository katalon-studio/docs, pull requests merged in 2019-11, with the labels that each got.

#567 jmeter integration
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/jmeter-integration.md
Labels: KS

#564 update DDT docs
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/ddt.md
Labels: KS

#563 Linux Docs Updated
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/katalon-studio-for-linux-console-mode.md
  pages/katalon-studio/docs/katalon-studio-gui-beta-for-linux.md
Labels: KS

#561 KA - Hide Cloud Agent Page
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: KA

#593 Update import test result from KS
  pages/katalon-analytics/docs/project-management-import-KS.md
Labels: KT

#595 Update image urls
  pages/katalon-analytics/docs/ka-integration-jira.md
Labels: KT

#596 Update glossary for KT
  pages/katalon-analytics/docs/ka-glossary.md
Labels: KT

#597 Update add page user role and permission to sidebar
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: KT

#592 Config Mail Server config for KTOP
  pages/katalon-analytics/docs/kt-op-mail-server.md
Labels: KT-OP

#598 Update TestOps term for Overview page
  pages/katalon-analytics/docs/ka-overview.md
Labels: KT

#591 Add KT OP Tree on Sidebar
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: KT-OP

#581 Create KTOP Installation Guide
  pages/katalon-analytics/docs/kt-op-installation.md
Labels: KT-OP

#599 Change TestOps term for Getting Started page
  pages/katalon-analytics/docs/getting-started.md
Labels: KT
