Repository katalon-studio/docs, pull requests merged in 2021-12, with the labels that each got.

#1452 K1-TDAP-273-Update-document-for-navigation-through-TestOps
  pages/katalon-analytics/docs/testops-navigation.md
Labels: Kat One

#1471 KS - TDAP-282 [Katalon Studio] 8.2.5 Beta Release Notes
  pages/katalon-studio/new/version-8x.md
Labels: 8.2.5 beta release

#1472 TDAP-283 TDAP-301 [Katalon Studio 8.2.5 Beta] Update Katalon Compact Utility docs
  pages/katalon-studio/docs/katalon-compact-utility.md
Labels: 8.2.5 beta release

#1468 KS-TDAP-100-Create-a-tutorial-for-analyzing-web-UI-test-results
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/tutorials/plan-test-suite.md
  pages/katalon-studio/tutorials/webui-review-and-analyze-test-suite-reports.md
Labels: KS, ks-revamp

#1470 WIP KS-TDAP-114-A-tutorial-for-using-Git-Submodules-to-share-common-resources
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/git-integration-submodules.md
Labels: KS

#1503 Fix wrong URL redirect link for security page
  faqs/security-and-privacy.html
Labels: enhancement

#1421 Kt release november UI changes
  pages/katalon-analytics/docs/create-plan.md
  pages/katalon-analytics/docs/kt-scheduler.md
Labels: TestOps

#1426 Kt release november UI changes 2
  pages/katalon-analytics/docs/bdd-test-results.md
  pages/katalon-analytics/docs/git-test-project.md
  pages/katalon-analytics/docs/ka-defects.md
  pages/katalon-analytics/docs/ka-integration-jira.md
  pages/katalon-analytics/docs/kt-change-result-pass-fail.md
  pages/katalon-analytics/docs/load-balancing-agents.md
  pages/katalon-analytics/docs/testops-june-rerun-results.md
  pages/katalon-studio/docs/katalon-analytics-beta-integration.md
  pages/katalon-studio/docs/ks_visual_testing.md
Labels: TestOps

#1428 Kt release november UI changes 3
  pages/katalon-analytics/docs/agents.md
  pages/katalon-analytics/docs/aws-eks.md
  pages/katalon-analytics/docs/compare-test-results.md
  pages/katalon-analytics/docs/docker.md
  pages/katalon-analytics/docs/kt-build.md
  pages/katalon-analytics/docs/kt-change-result-pass-fail.md
  pages/katalon-analytics/docs/kt-jira-config.md
  pages/katalon-analytics/docs/kt-release.md
  pages/katalon-analytics/docs/kt_kobiton_integration.md
  pages/katalon-analytics/docs/project-management-delete.md
  pages/katalon-analytics/docs/testops-may-filter-test-runs-list-by-build-name.md
Labels: TestOps

#1435 Update kt_run_parallel_agent.md
  pages/katalon-analytics/docs/kt_run_parallel_agent.md
Labels: TestOps, kt-revamps

#1439 Update code-repo.md
  pages/katalon-analytics/docs/code-repo.md
Labels: TestOps

#1440 Update view-test-cases.md
  pages/katalon-analytics/docs/view-test-cases.md
Labels: TestOps

#1475 Kt revamps delete content
  pages/katalon-analytics/docs/kt-change-result-pass-fail.md
  pages/katalon-analytics/docs/overwrite-test-run.md
Labels: kt-revamps

#1476 Update circleci.md
  pages/katalon-analytics/docs/circleci.md
Labels: kt-revamps

#1478 Update kt-upload-test-mocha.md
  pages/katalon-analytics/docs/kt-upload-test-mocha.md
Labels: TestOps, kt-revamps

#1479 Update kt-upload-test-jest.md
  pages/katalon-analytics/docs/kt-upload-test-jest.md
Labels: TestOps, kt-revamps

#1480 Update testops-uploader.md
  pages/katalon-analytics/docs/testops-uploader.md
  pages/katalon-analytics/docs/view-abnormal-web-services.md
Labels: TestOps

#1481 Update kt-upload-test-jasmine.md
  pages/katalon-analytics/docs/kt-upload-test-jasmine.md
Labels: TestOps, kt-revamps

#1482 Update kt-upload-test-pytest.md
  pages/katalon-analytics/docs/kt-upload-test-pytest.md
Labels: TestOps, kt-revamps

#1484 Update test-run-config.md
  pages/katalon-analytics/docs/test-run-config.md
Labels: kt-revamps

#1492 Update testops-releases-2021.md
  pages/katalon-analytics/docs/testops-releases-2021.md
Labels: TestOps

#1502 Update view-traceability-matrix.md
  pages/katalon-analytics/docs/view-traceability-matrix.md
Labels: TestOps

#1487 Create test-case-management-journey.md
  pages/katalon-analytics/docs/test-case-management-journey.md
Labels: TestOps

#1497 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: TestOps, kt-revamps

#1474 KS-TDAP-98-Create-an-article-for-keyboard-shortcuts-in-KS
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/keyboard-shortcuts.md
Labels: KS

#1477 KRE-TDAP-279-Update-the-KRE-activation-document
  pages/katalon-studio/docs/activate-KSE.md
Labels: KS

#1488 KR-TDAP-271-Create-a-tutorial-on-using-loops-and-conditionals
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-recorder/docs/Get Your Job Done/Automate Scenarios/conditional-cases.md
  pages/katalon-recorder/docs/Get Your Job Done/Automate Scenarios/how-to-use-conditional-statements-in-a-test-case.md
  pages/katalon-recorder/docs/Get Your Job Done/Data-driven testing/data-driven-testing.md
Labels: KR

#1419 KS - TDAP-263 - Revamp Test Case documents
  pages/katalon-studio/docs/call-test-case.md
  pages/katalon-studio/docs/create-test-case.md
  pages/katalon-studio/docs/fixtures-listeners.md
  pages/katalon-studio/docs/search.md
  pages/katalon-studio/docs/statements.md
  pages/katalon-studio/docs/test-case-management-with-tags.md
  pages/katalon-studio/docs/working-with-sensitive-text.md
Labels: ks-revamp

#1454 KS-TDAP-265-Revamp WebUI doc in the new configuration section
  pages/katalon-studio/docs/how-to-test-different-locales-with-desired-capabilities.md
  pages/katalon-studio/docs/import-export-test-artifact.md
  pages/katalon-studio/docs/internet-explorer-configurations.md
  pages/katalon-studio/docs/katalon-addon-for-chrome.md
  pages/katalon-studio/docs/record-web-utility.md
  pages/katalon-studio/docs/setup-winappdriver.md
  pages/katalon-studio/docs/variable-types.md
  pages/katalon-studio/how-to-guides/set-new-default-JRE.md
Labels: ks-revamp

#1459 KS-TDAP-265-Revamp mobile docs for the new configuration section
  pages/katalon-studio/docs/configure-android-studio.md
  pages/katalon-studio/docs/installing-webdriveragent-for-ios-devices.md
  pages/katalon-studio/tutorials/mobile-android-setup.md
  pages/katalon-studio/tutorials/mobile-create-ios-test-case.md
Labels: ks-revamp

#1469 KS-TDAP-293-Revamp migration from other tools section
  pages/katalon-studio/docs/import-selenium-ide.md
  pages/katalon-studio/docs/selenium-testng-junit-migration.md
Labels: ks-revamp

#1473 TDAP-259 TDAP-281 Katalon Studio Preferences revamp
  pages/katalon-studio/docs/import-preferences.md
  pages/katalon-studio/docs/katalon-studio-preferences.md
  pages/katalon-studio/docs/mobile-preferences.md
  pages/katalon-studio/docs/object-spy-preferences.md
  pages/katalon-studio/docs/proxy-preferences.md
  pages/katalon-studio/docs/test-case-preferences.md
  pages/katalon-studio/docs/theme.md
  pages/katalon-studio/docs/troubleshoot-activation-problems.md
  pages/katalon-studio/docs/troubleshoot-globalvariable-special-character.md
Labels: ks-revamp

#1485 KS-TDAP-280-Intro desired capabilities revamp
  pages/katalon-analytics/docs/bdd-settings.md
  pages/katalon-studio/docs/desired-capabilities-at-runtime.md
  pages/katalon-studio/docs/desired-capabilities-custom-settings.md
  pages/katalon-studio/docs/desired-capabilities-remote-settings.md
  pages/katalon-studio/docs/desired-capabilities-settings-mobile.md
  pages/katalon-studio/docs/desired-capabilities-settings-webui.md
  pages/katalon-studio/docs/desired-capabilities-settings-windows.md
  pages/katalon-studio/docs/import-export-desired-capabilities.md
  pages/katalon-studio/docs/introduction-to-desired-capabilities.md
  pages/katalon-studio/docs/product-availability-matrix.md
  pages/katalon-studio/docs/selenium-grid-integration.md
  pages/katalon-studio/docs/start-browsers-in-private-mode.md
Labels: ks-revamp

#1494 KS - TDAP-258 Getting Started Overview
  pages/katalon-studio/docs/get-started-overview.md
Labels: ks-revamp

#1486 KS-TDAP-298-Revamp sidebar Sprint 6
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: ks-revamp

#1514 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: KS, ks-revamp

#1512 Ks tdap 266 testops integration
  pages/katalon-studio/docs/execute_tests_periodically_on_remote_machines.md
  pages/katalon-studio/docs/testops-integration.md
  pages/katalon-studio/docs/view-execution-list.md
Labels: KS, ks-revamp

#1515 Fixing typo + bug
  pages/katalon-studio/docs/desired-capabilities-remote-settings.md
  pages/katalon-studio/docs/introduction-to-desired-capabilities.md
Labels: bug

#1507 Update aws-eks.md
  pages/katalon-analytics/docs/aws-eks.md
Labels: TestOps

#1498 TDAP-322 [KS] Error while running Android tests on Windows machine
  pages/katalon-studio/docs/troubleshoot-common-execution-exceptions-web-test.md
  pages/katalon-studio/docs/troubleshooting-automated-mobile-testing.md
Labels: KS

#1504 KS-TDAP-254-Revamp sample project section-PART 1
  pages/katalon-studio/docs/health-care-prj.md
  pages/katalon-studio/docs/sample-projects.md
  pages/katalon-studio/docs/shopping-cart-prj.md
Labels: ks-revamp

#1508 KS-TDAP-255-Revamp sample project mobile docs-PART 2
  pages/katalon-studio/docs/android-sample-prj.md
  pages/katalon-studio/docs/ios-sample-prj.md
Labels: ks-revamp

#1522 TDAP-201 As a total novice, I want to read one introduction about simple concepts on Katalon Studio
  pages/katalon-studio/docs/katalon-studio-overview.md
  pages/katalon-studio/docs/overview.md
Labels: ks-revamp

#1523 KS-TDAP-313-Revamp sidebar sprint 7
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/get-started-overview.md
  pages/katalon-studio/tutorials/quick_start.md
  pages/katalon-studio/tutorials/set-up-overview.md
Labels: ks-revamp

#1509 K1-TDAP-311-Create-a-guide-for-User-Profile-Management
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/manage-user-profile.md
Labels: Kat One

#1511 K1 release UI updates
  pages/katalon-studio/docs/grant-katalon-licenses.md
  pages/katalon-studio/docs/license-management.md
  pages/katalon-studio/docs/remove-license.md
Labels: Kat One

#1528 K1 release dec27
  pages/katalon-studio/docs/grant-katalon-licenses.md
  pages/katalon-studio/docs/license-management.md
  pages/katalon-studio/docs/remove-license.md
Labels: Kat One

#1490 K1-TDAP-289-Update-the-SSO-Configuration-document
  pages/katalon-analytics/docs/sso-settings.md
Labels: Kat One

#1526 KS-TDAP-347 Update identity configuration for SSO document
  pages/katalon-analytics/docs/sso-settings.md
Labels: TestOps
