Repository katalon-studio/docs, pull requests merged in 2021-06, with the labels that each got.

#1138 Install and use packed extensions
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/Install-packed-extension-chrome.md
  pages/katalon-studio/docs/license-subscription.md
Labels: Extra Small

#1144 Chrome with profile update
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/Install-packed-extension-chrome.md
  pages/katalon-studio/docs/webui-take-screenshot.md
Labels: Small

#1142 First draft for guide on screenshot timestamps using WebUI keywords
  pages/katalon-studio/docs/webui-take-screenshot.md
Labels: Small

#1128 Release note 8.0.5
  pages/katalon-studio/new/version-8x.md
Labels: Release 8.0.5, Small

#1156 redirect url
  pages/katalon-analytics/docs/kt-jira-config.md
Labels: Extra Small

#1149 Kt release june rerun result
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/testops-june-rerun-results.md
Labels: Extra Small, TestOps

#1140 Update ka-overview.md
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/ka-overview.md
Labels: Extra Small, kt-revamps

#1143 Revamps kt create organization
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/kt-create-organization.md
Labels: Small, kt-revamps

#1145 Revamps kt invite user org
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/kt_invite_user_org.md
Labels: Medium, kt-revamps

#1146 Revamps testops setup team
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/setup-team.md
Labels: Small, kt-revamps

#1148 Kt-revamps-getting-started
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/getting-started.md
Labels: Extra Small, kt-revamps

#1157 Update kt-jira-config.md
  pages/katalon-analytics/docs/kt-jira-config.md
Labels: Small, kt-revamps

#1155 Update kt-jira-release.md
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/kt-jira-release.md
Labels: Small, kt-revamps

#1154 Update jira-gadgets.md
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/jira-gadgets.md
Labels: Extra Small, kt-revamps

#1153 Kt revamps releases
  pages/katalon-analytics/docs/kt-release.md
Labels: Small, kt-revamps

#1161 Update testops-releases-2021.md
  pages/katalon-analytics/docs/testops-releases-2021.md
Labels: Extra Small, TestOps

#1169 Create import-selenium-ide.md
  pages/katalon-recorder/docs/Getting Started/import-selenium-ide.md
Labels: Extra Small

#1172 KR 5.5 for review
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-recorder/docs/Get Your Job Done/Execute Scenarios/Self-healing.md
  pages/katalon-recorder/docs/Get Your Job Done/Execute Scenarios/Use the Command-Line Runner.md
  pages/katalon-recorder/docs/Get Your Job Done/Extend Katalon Recorder/import-selenium-ide.md
  pages/katalon-recorder/docs/Get Your Job Done/Extend Katalon Recorder/side-kr-command-compatibility.md
  pages/katalon-recorder/docs/Getting Started/overview.md
  pages/katalon-recorder/docs/Getting Started/whats-new/whats-new-54x.md
  pages/katalon-recorder/docs/Getting Started/whats-new/whats-new.md
Labels: Large
