Repository katalon-studio/docs, pull requests merged in 2021-10, with the labels that each got.

#1344 KS-TDAP 118-Fix sidebar url
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/how-to-test-different-locales-with-desired-capabilities.md
Labels: bug, KS, Extra Small

#1337 K1 license update
  pages/katalon-studio/docs/license.md
  pages/katalon-studio/docs/use-online-license.md
Labels: Extra Small

#1348 Change "licensed user" and some links
  pages/katalon-studio/docs/activate-KSE.md
Labels: Extra Small

#1291 KS-Tdap-43-Enhacing outdated shadow dom doc
  pages/katalon-studio/tutorials/shadow_dom_elements_testing.md
Labels: KS, Medium

#1259 KS - TDAP-22- Improving handle webdriver doc
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/Handle-webdrivers-with-event-firing-webdrivers.md
  pages/katalon-studio/docs/handle-webdriver.md
  pages/katalon-studio/docs/handle-webdrivers.md
  pages/katalon-studio/docs/terminate-webdriver.md
  pages/katalon-studio/docs/update-or-downgrade-webdrivers.md
Labels: KS, Large

#1351 Fix sidebar broken link
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: bug, Extra Small

#1340 KS - TDAP-183 - Create documents for Katalon Compact Utility
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/Install-packed-extension-chrome.md
  pages/katalon-studio/docs/katalon-compact-utility.md
Labels: KS, Small
