Repository katalon-studio/docs, pull requests merged in 2021-03, with the labels that each got.

#1021 Update mobile-verify-element-exist.md & mobile-verify-element-not-exist.md
  pages/katalon-studio/docs/mobile-verify-element-exist.md
  pages/katalon-studio/docs/mobile-verify-element-not-exist.md
Labels: Extra Small

#1020 TO new doc
  pages/katalon-analytics/docs/kt-build.md
  pages/katalon-analytics/docs/testops-terminology.md
Labels: Small

#1022 Update external-libraries.md
  pages/katalon-studio/docs/external-libraries.md
Labels: Extra Small

#1008 Update Jira configuration
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/agents.md
  pages/katalon-analytics/docs/aws-eks.md
  pages/katalon-analytics/docs/code-repo.md
  pages/katalon-analytics/docs/create-plan.md
  pages/katalon-analytics/docs/docker.md
  pages/katalon-analytics/docs/git-test-project.md
  pages/katalon-analytics/docs/ka-api-key.md
  pages/katalon-analytics/docs/kt-build.md
  pages/katalon-analytics/docs/kt-jira-config.md
  pages/katalon-analytics/docs/kt-jira-release.md
  pages/katalon-analytics/docs/kt-noti-email.md
  pages/katalon-analytics/docs/kt-remote-execution.md
  pages/katalon-analytics/docs/load-balancing-agents.md
  pages/katalon-analytics/docs/requirement-coverage.md
  pages/katalon-analytics/docs/slack-integration.md
  pages/katalon-analytics/docs/testops-terminology.md
  pages/katalon-analytics/docs/testops-uploader.md
  pages/katalon-analytics/docs/view-reports-overview.md
  pages/katalon-analytics/docs/view-test-cases.md
Labels: Large

#1023 Core 1.1.0 (WIP)
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/core-1.x.md
  pages/katalon-analytics/docs/new-core-11.md
Labels: Small

#1024 update sidebar
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: Extra Small

#1025 Fix typo in Create Your First Plugin tutorial sample code
  pages/katalon-store/docs/publisher/create-plugin.md
Labels: Extra Small

#1027 update url
  pages/katalon-analytics/docs/load-balancing-agents.md
Labels: Extra Small

#1017 Update database-settings.md
  pages/katalon-studio/docs/database-settings.md
Labels: Medium

#999 Update Profile
  pages/katalon-studio/docs/execution-profile-v54.md
Labels: Medium

#1029 Update database-settings.md
  pages/katalon-studio/docs/database-settings.md
Labels: Extra Small

#1028 Update external-libraries.md
  pages/katalon-studio/docs/external-libraries.md
Labels: Extra Small

#1026 Setting screen resolution for running UI tests in Azure Pipelines
  pages/katalon-studio/docs/azure-devops-extension.md
Labels: Extra Small

#1019 Getting started
  README.md
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/bdd-settings.md
  pages/katalon-analytics/docs/code-repo.md
  pages/katalon-analytics/docs/compare-test-results.md
  pages/katalon-analytics/docs/create-plan.md
  pages/katalon-analytics/docs/execute-test-run.md
  pages/katalon-analytics/docs/getting-started.md
  pages/katalon-analytics/docs/kt-jira-release.md
  pages/katalon-analytics/docs/kt-release.md
  pages/katalon-analytics/docs/kt-upload-test-jest.md
  pages/katalon-analytics/docs/kt_invite_user_org.md
  pages/katalon-analytics/docs/load-balancing-agents.md
  pages/katalon-analytics/docs/view-ci-plans.md
  pages/katalon-studio/docs/ks_visual_testing.md
Labels: Large

#1032 Update katalon_studio_videos_sidebar.yml
  _data/sidebars/katalon_studio_videos_sidebar.yml
Labels: Extra Small

#1033 Update Import Restful requests with OpenApi
  pages/katalon-studio/docs/import-openapi30.md
  pages/katalon-studio/docs/import-rest-requests-from-swagger-20.md
Labels: Small

#1031 Rahul Rathore
  pages/katalon-studio/videos/api_testing_katalon_studio_delete_request.md
  pages/katalon-studio/videos/api_testing_katalon_studio_dynamic_data_in_request_body.md
  pages/katalon-studio/videos/api_testing_katalon_studio_get_request_verify_response.md
  pages/katalon-studio/videos/api_testing_katalon_studio_handling_jwt.md
  pages/katalon-studio/videos/api_testing_katalon_studio_post_request_verify_response_rahul.md
  pages/katalon-studio/videos/api_testing_katalon_studio_put_request_verify_response.md
  pages/katalon-studio/videos/api_testing_katalon_studio_put_request_verify_response_rahul.md
  pages/katalon-studio/videos/api_testing_katalon_studio_version_5_4.md
Labels: Small

#1035 Rahul Rathore
  pages/katalon-studio/videos/api_testing_katalon_studio_dynamic_data_in_request_body.md
  pages/katalon-studio/videos/api_testing_katalon_studio_get_request_verify_response.md
  pages/katalon-studio/videos/api_testing_katalon_studio_handling_jwt.md
  pages/katalon-studio/videos/api_testing_katalon_studio_post_request_verify_response_rahul.md
  pages/katalon-studio/videos/api_testing_katalon_studio_put_request_verify_response_rahul.md
Labels: Extra Small

#1036 KB Tutorials
  pages/katalon-studio/videos/introduction_to_katalon_studio.md
  pages/katalon-studio/videos/mobile_testing_using_katalon_studio.md
Labels: Extra Small

#1038 Rahul Rathore
  pages/katalon-studio/videos/api_testing_katalon_studio_get_request_verify_response.md
  pages/katalon-studio/videos/api_testing_katalon_studio_handling_jwt.md
  pages/katalon-studio/videos/api_testing_katalon_studio_post_request_verify_response_rahul.md
  pages/katalon-studio/videos/api_testing_katalon_studio_put_request_verify_response_rahul.md
Labels: Extra Small

#1037 Update katalon_studio_videos_sidebar.yml
  _data/sidebars/katalon_studio_videos_sidebar.yml
Labels: Extra Small

#1040 Update katalon_studio_videos_sidebar.yml
  _data/sidebars/katalon_studio_videos_sidebar.yml
Labels: Extra Small

#1046 Update katalon-studio-github-action.md
  pages/katalon-studio/docs/katalon-studio-github-action.md
Labels: Extra Small

#1047 Update Edge availability to KR's overview docs
  pages/katalon-recorder/docs/Getting Started/overview.md
Labels: Extra Small

#1048 add webhook
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/kt-change-result-pass-fail.md
  pages/katalon-analytics/docs/slack-integration.md
Labels: Extra Small
