Repository katalon-studio/docs, pull requests merged in 2021-09, with the labels that each got.

#1243 Kse understand waiting keywords
  pages/katalon-studio/docs/failure-handling.md
  pages/katalon-studio/docs/understanding-waiting-keywords.md
Labels: KS, Extra Small

#1273 KS-TDAP-150-License Utilization Dashboard
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/license-utilization-dashboard.md
Labels: Small

#1275 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: Extra Small

#1242 Create testops-pricing-model.md
  pages/katalon-analytics/docs/testops-pricing-model.md
Labels: Medium, TestOps

#1244 Kt revamps aws eks
  pages/katalon-analytics/docs/aws-eks.md
Labels: Extra Small, kt-revamps

#1266 Kt revamps docker
  pages/katalon-analytics/docs/docker.md
Labels: Extra Small, kt-revamps

#1265 KS - TDAP-130 - Update documents of sideload
  pages/katalon-studio/docs/app-center.md
Labels: Medium

#1258 Enhance Terminate Execution Conditionally docs
  pages/katalon-studio/tutorials/condition-to-stop.md
Labels: enhancement, KS, Extra Small

#1255 TDAP-65-Offline plugin installation
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/install-plugin-offline.md
  pages/katalon-studio/docs/kse-use-plugins.md
Labels: KS, Small

#1276 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: Extra Small

#1252 TDAP-131-Android home environment variable
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/how-to-guides/specify-android-home-path.md
  pages/katalon-studio/new/version-8x.md
Labels: KS, Extra Small, Release 8.1.0

#1241 Add simpler guide to CircleCI Integration - Katalon Orb
  pages/katalon-studio/docs/integration-circleci.md
Labels: KS, Small

#1254 TDAP-88 - Improvement on Azure DevOps Test Plans doc
  pages/katalon-studio/docs/azure-devops-test-plans.md
Labels: enhancement, KS, Small, Release 8.1.0

#1280 MKT-853 [ Add Academy into topnav ]
  _data/topnav.yml
Labels: Extra Small

#1282 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: Extra Small, TestOps

#1218 New version of Katalon for Azure DevOps Extension
  pages/katalon-studio/docs/azure-devops-extension.md
Labels: KS, Extra Small

#1278 Tdap-46-Correct mistake in the api document as feedback on the forum.
  javadoc/com/kms/katalon/core/testobject/RequestObject.html
Labels: bug, Extra Small

#1287 Update intro-RE.md because of obsolete description
  pages/katalon-studio/docs/intro-RE.md
Labels: Extra Small

#1279 Update testops-pricing-model.md
  pages/katalon-analytics/docs/testops-pricing-model.md
Labels: Extra Small, TestOps

#1272 KS-TDAP-144-PoC- Data Driven Testing with ADO
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/associated-ADO-Test-Case-IDs.md
  pages/katalon-studio/docs/dependencies-management-gradle-support.md
Labels: KS, Extra Small, 8.1.1 alpha

#1281 Update license-server.md
  pages/katalon-studio/docs/license-server.md
Labels: Extra Small

#1284 Update failure-handling.md
  pages/katalon-studio/docs/failure-handling.md
Labels: Extra Small

#1292 Update cucumber-kw-run-feature-file-tag.md
  pages/katalon-studio/docs/cucumber-kw-run-feature-file-tag.md
Labels: Extra Small

#1296 Update App Center docs: Adding Error Note for macOS users
  pages/katalon-studio/docs/app-center.md
Labels: KS, Extra Small

#1302 Update git-test-project.md
  pages/katalon-analytics/docs/git-test-project.md
Labels: Extra Small, TestOps

#1317 KS-TDAP-154-Update for documents for installing web driver agent for iOS
  pages/katalon-studio/docs/installing-webdriveragent-for-ios-devices.md
Labels: KS, Small

#1309 Kt release UI updates execute test run
  pages/katalon-analytics/docs/kt-scheduler.md
Labels: Extra Small, TestOps

#1310 Kt release UI updates on schedule test run
  pages/katalon-analytics/docs/create-plan.md
Labels: Small, TestOps

#1294 KS - TDAP-108 - Passing feature file/scenario tags at runtime when building with Jenkins
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/how-to-guides/jenkins-tags-runtime.md
Labels: KS, Extra Small

#1261 KS TDAP-44 - Flutter-based Application testing workarounds and troubleshooting
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/troubleshooting-automated-mobile-testing.md
  pages/katalon-studio/tutorials/flutter-based-application-testing.md
Labels: KS, Medium

#1327 Kt release update schedule test run
  pages/katalon-analytics/docs/create-plan.md
  pages/katalon-analytics/docs/grid-testops-cloud.md
Labels: Extra Small

#1331 kt-release-notes-september-no-conflict
  pages/katalon-analytics/docs/testops-releases-2021.md
Labels: Extra Small

#1332 Update testops-releases-2021.md
  pages/katalon-analytics/docs/testops-releases-2021.md
Labels: Extra Small

#1277 Tdap-101-How to capture elements hybrid Android apps
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/how-to-capture-objects-in-hybrid-apps.md
Labels: KS, Small

#1300 KS-TDAP-105-How to skip test cases
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/how-to-skip-test-case.md
Labels: KS, Small

#1268 Tdap 118 - KS - how to test different browsers locales in Chrome with desired capabilities
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/how-to-test-different-locales-with-desired-capabilities.md
Labels: KS, Medium

#1305 KS - TDAP-156 - Create AWS Device Farm Integration docs
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/aws-device-farm-integration.md
Labels: KS, Small

#1314 Create org-level-roles-privileges.md
  pages/katalon-analytics/docs/org-level-roles-privileges.md
Labels: Medium

#1316 K1 release update testops user mgt
  pages/katalon-analytics/docs/kt_invite_user_org.md
Labels: Medium

#1329 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: Extra Small

#1333 Update org-level-roles-privileges.md
  pages/katalon-analytics/docs/org-level-roles-privileges.md
Labels: Medium

#1271 Tdap-141-Enhancing reusing dc across projects
  pages/katalon-studio/docs/import-export-desired-capabilities.md
Labels: KS, Small

#1286 License Revamp - TDAP-145 TDAP-42 TDAP-74 - Overview and types of licenses
  pages/katalon-studio/docs/intro-RE.md
  pages/katalon-studio/docs/ks-vs-kse.md
  pages/katalon-studio/docs/license.md
  pages/katalon-studio/docs/online-offline-licenses.md
  pages/katalon-studio/docs/overview.md
Labels: Extra Large, license-revamp

#1288 License revamps grant licenses
  pages/katalon-studio/docs/how-to-create-kse-offline-license.md
  pages/katalon-studio/docs/re-offline-license.md
  pages/katalon-studio/docs/use-online-license.md
Labels: Medium, license-revamp

#1297 License revamps license management
  pages/katalon-studio/docs/license-management.md
  pages/katalon-studio/docs/transfer-license.md
Labels: Medium, license-revamp

#1298 KS - TDAP-157 - Monitor Licenses
  pages/katalon-analytics/docs/usage-dashboard.md
  pages/katalon-studio/docs/view-license-details.md
Labels: KS, Small, license-revamp

#1299 KS - TDAP-172 - Configure Idle Timeout
  pages/katalon-analytics/docs/license-idle-timeout.md
Labels: KS, Extra Small, license-revamp

#1301 KS - TDAP-173 - Katalon License Subscription revamp
  pages/katalon-studio/docs/license-KT.md
  pages/katalon-studio/docs/license-po.md
  pages/katalon-studio/docs/license-quote.md
  pages/katalon-studio/docs/license-subscription.md
  pages/katalon-studio/docs/subscription-kstore.md
Labels: Medium, license-revamp

#1303 KS - License revamp - TDAP-143 - Cancel subscription
  pages/katalon-studio/docs/cancel-subs.md
Labels: KS, Extra Small, license-revamp

#1311 KS - TDAP-163 - License Activation Revamp
  pages/katalon-studio/docs/activate-KSE.md
  pages/katalon-studio/docs/configure-proxy.md
  pages/katalon-studio/docs/install-RE.md
  pages/katalon-studio/docs/katalon-studio-activation-since-70.md
  pages/katalon-studio/docs/machine-id.md
  pages/katalon-studio/docs/trial-free-plans.md
Labels: KS, Large, license-revamp

#1313 KS - TDAP-177 - Change License Plans
  pages/katalon-studio/docs/billing-info.md
  pages/katalon-studio/docs/kre-devops-sunset.md
  pages/katalon-studio/docs/upgrade-subs.md
Labels: KS, Medium, license-revamp

#1315 KS - TDAP-178 - Troubleshooting license activation revamp
  pages/katalon-studio/docs/session-termination.md
  pages/katalon-studio/docs/troubleshoot-activation-problems.md
  pages/katalon-studio/docs/troubleshooting.md
Labels: KS, Extra Small, license-revamp

#1285 TDAP-37 License sidebar revamp
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/license-server.md
Labels: Small, license-revamp

#1335 Update org-level-roles-privileges.md
  pages/katalon-analytics/docs/org-level-roles-privileges.md
Labels: Extra Small

#1324 KS - TDAP-82 - Update the information about the execution profile is not applied to TCS when customize the email subject
  pages/katalon-studio/docs/execution-settings.md
Labels: KS, Extra Small, ks-revamp

#1320 KS - TDAP-146 - Create Troubleshooting common exceptions document for Windows
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/introduction-to-desired-capabilities.md
  pages/katalon-studio/docs/troubleshooting-common-exceptions-windows.md
  pages/katalon-studio/docs/troubleshooting.md
Labels: KS, Small, ks-revamp

#1226 KS - TDAP-66 TDAP-159 Improve the step by step guide to Github SSH and HTTPS authentication
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/bitbucket-intergration.md
  pages/katalon-studio/docs/git-integration-authentication.md
  pages/katalon-studio/docs/git-integration.md
Labels: KS, Large

#1338 Update-Purchase-Licenses
  pages/katalon-studio/docs/license-subscription.md
Labels: Extra Small
