Repository katalon-studio/docs, pull requests merged in 2021-07, with the labels that each got.

#1167 Update kt-release.md
  pages/katalon-analytics/docs/kt-release.md
Labels: Extra Small

#1163 Kt revamps git test project
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/git-test-project.md
Labels: Small, kt-revamps

#1162 Update code-repo.md
  pages/katalon-analytics/docs/code-repo.md
Labels: Extra Small, kt-revamps

#1166 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: Extra Small, kt-revamps

#1175 Kt revamps schedule test runs
  pages/katalon-analytics/docs/create-plan.md
Labels: Extra Small, kt-revamps

#1131 Remove nodejs-testing
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/upload-junit-and-testng.md
Labels: Extra Small

#1173 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: Extra Small

#1176 update execute-test-run.md
  pages/katalon-analytics/docs/execute-test-run.md
Labels: Extra Small

#1174 Kt revamps execute test runs by trigger
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/kt-scheduler.md
Labels: Small, kt-revamps

#1177 trial plans update
  pages/katalon-studio/docs/trial-free-plans.md
Labels: Extra Small

#1184 Update troubleshoot-common-execution-exceptions-web-test.md
  pages/katalon-studio/docs/troubleshoot-common-execution-exceptions-web-test.md
Labels: Extra Small

#1185 Kt revamps delete upload test suite
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/ks_upload_project_kt.md
Labels: Extra Small

#1180 Kt revamps katalon analytic beta integration
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/katalon-analytics-beta-integration.md
Labels: Small, kt-revamps

#1178 Kt revamps install kt agent
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/install_kt_agent.md
Labels: Extra Small, kt-revamps

#1179 Kt revamps agents
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/agents.md
Labels: Medium, kt-revamps

#1181 Kt revamps upload manually from ks to kto
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/project-management-import-KS.md
Labels: Extra Small, kt-revamps

#1190 Update link to Swagger on product-availability-matrix.md
  pages/katalon-studio/docs/product-availability-matrix.md
Labels: Large

#1136 Updates troubleshooting activation probs
  pages/katalon-studio/docs/troubleshoot-activation-problems.md
Labels: Small

#1193 Kt revamps bdd test results
  pages/katalon-analytics/docs/bdd-test-results.md
Labels: Small, kt-revamps

#1194 Kt revamps ka integration jira
  pages/katalon-analytics/docs/ka-integration-jira.md
Labels: Extra Small, kt-revamps

#1195 Kt revamps ka defects
  pages/katalon-analytics/docs/ka-defects.md
Labels: Small, kt-revamps

#1168 TADP-59: Update video
  _data/sidebars/katalon_studio_videos_sidebar.yml
  pages/katalon-studio/videos/adding_new_property_for_test_object.md
  pages/katalon-studio/videos/creating_execution_profile_in_katalon.md
  pages/katalon-studio/videos/creating_parameterized_test_object_katalon.md
  pages/katalon-studio/videos/developing_custom_keyword_for_grid.md
  pages/katalon-studio/videos/handling_complex_grid_in_katalon_studio.md
  pages/katalon-studio/videos/handling_keyboard_action_with_katalon.md
  pages/katalon-studio/videos/handling_mouse_click_with_katalon.md
  pages/katalon-studio/videos/handling_multiple_set_test_data.md
  pages/katalon-studio/videos/introduction_to_katalon_analytics.md
  pages/katalon-studio/videos/parallel_test_execution_in_katalon.md
  pages/katalon-studio/videos/reading_value_from_grid.md
  pages/katalon-studio/videos/removing_property_from_test_object.md
  pages/katalon-studio/videos/report_analysis_in_katalon_studio.md
  pages/katalon-studio/videos/running_script_in_headless_browser.md
  pages/katalon-studio/videos/setting_up_and_creating_teardown_from_scriptmode.md
  pages/katalon-studio/videos/test_case_execution_using_different_profle_in_katalon_studio.md
  pages/katalon-studio/videos/test_execution_on_remote_machines.md
  pages/katalon-studio/videos/test_execution_using_katalon_plugin_for_jenskin.md
  pages/katalon-studio/videos/test_suite_creation_and_execution_in_katalon.md
  pages/katalon-studio/videos/updating_existing_property_for_test_object.md
  pages/katalon-studio/videos/uploading_reports_to_katalon_analytics.md
  pages/katalon-studio/videos/using_parameterized_test_object_in_katalon_studio.md
  pages/katalon-studio/videos/where_to_access_katalon_analytics.md
  pages/katalon-studio/videos/white_loop_in_katalon_studio.md
Labels: Large

#1203 Update white_loop_in_katalon_studio.md
  pages/katalon-studio/videos/white_loop_in_katalon_studio.md
Labels: Extra Small

#1202 Update selenium-testng-junit-migration.md
  pages/katalon-studio/docs/selenium-testng-junit-migration.md
Labels: Extra Small

#1212 Fixing typo in video path/url
  pages/katalon-studio/videos/while_loop_in_katalon_studio.md
Labels: Extra Small

#1199 Update-links-to-academy-2
  pages/katalon-analytics/docs/ka-overview.md
  pages/katalon-studio/docs/create-test-case.md
  pages/katalon-studio/docs/getting-started.md
  pages/katalon-studio/docs/import-selenium-ide.md
  pages/katalon-studio/docs/jenkins-plugin-windows.md
  pages/katalon-studio/docs/record-web-utility.md
  pages/katalon-studio/docs/selenium-testng-junit-migration.md
  pages/katalon-studio/tutorials/introduction-to-web-testing.md
  pages/katalon-studio/tutorials/introduction_api_testing.md
Labels: Extra Small

#1213 Test ops july 26 release
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/auto-distributed-execution.md
  pages/katalon-analytics/docs/testops-releases-2021.md
Labels: Small

#1188 Adjusted-format-fixtures-listeners
  pages/katalon-studio/docs/fixtures-listeners.md
Labels: Small

#1210 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: Extra Small

#1208 Create record-screen-based-videos.md
  pages/katalon-studio/docs/record-screen-based-videos.md
Labels: Extra Small

#1207 Editorial capture screenshots
  pages/katalon-studio/docs/capture-screenshots.md
Labels: Small

#1209 Update screenshots-videos.md
  pages/katalon-studio/docs/screenshots-videos.md
Labels: Medium

#1071 Web UI - Plan Test Suite
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/tutorials/plan-test-suite.md
Labels: Extra Small

#1214 Update testops-april-release-trial-plans.md
  pages/katalon-analytics/docs/testops-april-release-trial-plans.md
Labels: Extra Small, TestOps

#1220 Ks update broken links
  pages/katalon-studio/docs/record-screen-based-videos.md
  pages/katalon-studio/docs/screenshots-videos.md
Labels: Extra Small

#1219 Update-add-video-migrate-selenium
  pages/katalon-studio/docs/selenium-testng-junit-migration.md
Labels: Extra Small

#1229 Fixing #1228
  _data/sidebars/katalon_studio_videos_sidebar.yml
  pages/katalon-studio/videos/test_execution_using_katalon_plugin_for_jenskin.md
Labels: Extra Small

#1205 Kt revamps update schedule
  pages/katalon-analytics/docs/create-plan.md
  pages/katalon-analytics/docs/view-ci-plans.md
Labels: Extra Small, kt-revamps

#1206 Update load-balancing-agents.md
  pages/katalon-analytics/docs/load-balancing-agents.md
Labels: Small, kt-revamps

#1211 Update ks_visual_testing.md
  pages/katalon-studio/docs/ks_visual_testing.md
Labels: Medium, kt-revamps

#1204 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: Extra Small, kt-revamps
