Repository katalon-studio/docs, pull requests merged in 2021-11, with the labels that each got.

#1398 TDAP-50-Remove-whats-new-section-in-navbar
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/kte-whats-new-in-april-release.md
  pages/katalon-analytics/docs/new-core-11.md
  pages/katalon-recorder/docs/Getting Started/whats-new/whats-new-53x.md
  pages/katalon-recorder/docs/Getting Started/whats-new/whats-new-54x.md
  pages/katalon-recorder/docs/Getting Started/whats-new/whats-new.md
  pages/katalon-studio/new/what-is-new-78.md
  pages/katalon-studio/new/what-is-new-79.md
  pages/katalon-studio/new/what-is-new-800.md
  pages/katalon-studio/new/what-is-new-810.md
Labels: Large

#1395 Testcloud beta release
  pages/katalon-testcloud/integrate-testcloud-with-testops.md
  pages/katalon-testcloud/testcloud-overview.md
Labels: Small, TestCloud

#1401 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: Extra Small, TestCloud

#1380 KS - TDAP-212 - Improve Document related to Katalon with Linux
  pages/katalon-studio/docs/getting-started.md
  pages/katalon-studio/docs/katalon-studio-gui-beta-for-linux.md
  pages/katalon-studio/tutorials/mobile-android-setup.md
  pages/katalon-studio/tutorials/mobile-ios-setup.md
Labels: KS, Medium

#1383 Kt release override test results
  pages/katalon-analytics/docs/kt-change-result-pass-fail.md
  pages/katalon-analytics/docs/testops-may-filter-test-runs-list-by-build-name.md
Labels: Small, TestOps

#1388 K1 release users joining org
  pages/katalon-analytics/docs/kt-users-joining-org.md
Labels: Extra Small, Kat One

#1402 Update compare-test-results.md
  pages/katalon-analytics/docs/compare-test-results.md
Labels: Extra Small, TestOps

#1404 Update testops-releases-2021.md
  pages/katalon-analytics/docs/testops-releases-2021.md
Labels: Extra Small, TestOps

#1373 Update kt_invite_user_org.md
  pages/katalon-analytics/docs/kt_invite_user_org.md
Labels: Extra Small, Kat One

#1406 K1 release testops navigation doc
  pages/katalon-analytics/docs/testops-navigation.md
Labels: Small, Kat One

#1411 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: Extra Small, Kat One

#1360 KS-TDAP-110-Create-separate-web-image-based-testing-guide
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/manage-web-test-object.md
  pages/katalon-studio/docs/web-image-based-object-recognition.md
  pages/katalon-studio/docs/web-image-based-testing.md
Labels: KS, Medium, ks-revamp

#1390 KS-TDAP-117-Recording and playing back sap automation scripts
  pages/katalon-studio/docs/katalon-sap-scripting-tracker.md
Labels: KS, Small

#1413 KS-SAP-Update sidebar
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: bug, Extra Small

#1415 TDAP-236-Implement-in-app-survey
  _layouts/docs.html
Labels: question

#1412 KS-TDAP-238-Add documents for WebUI.findWebElements and WebUI.findWebElement
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/webui-find-web-element.md
  pages/katalon-studio/docs/webui-find-web-elements.md
Labels: KS, Medium

#1381 TDAP-102-Create-a-tutorial-for-ddt-with-web-service
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/ddt-with-web-service.md
Labels: Small

#1417 Kt revamps update redirect links
  pages/katalon-analytics/docs/kt_install_premises_docker.md
  pages/katalon-analytics/docs/kt_invite_user_org.md
Labels: kt-revamps

#1416 Update ka-api-key.md
  pages/katalon-analytics/docs/ka-api-key.md
Labels: kt-revamps

#1427 KS-TDAP-106-Katalon docker image guide
  pages/katalon-studio/docs/docker.md
Labels: KS

#1433 Kt revamps kt remote execution
  pages/katalon-analytics/docs/create-plan.md
  pages/katalon-analytics/docs/kt-remote-execution.md
Labels: kt-revamps

#1429 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: kt-revamps

#1430 Update ka-overview.md
  pages/katalon-analytics/docs/ka-overview.md
Labels: kt-revamps

#1396 KS-TDAP-234-Revamp & Merge Unique Capabilities into Support Technologies doc
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/product-availability-matrix.md
  pages/katalon-studio/docs/unique-capabilities.md
Labels: KS, Extra Large

#1414 KS-TDAP-230-Fix-the-broken-link-on-the-Rally-Integration-document
  pages/katalon-studio/docs/rally-integration.md
Labels: Extra Small

#1424 K1-TDAP-269-Update-SSO-configurations-for-existing-users
  pages/katalon-analytics/docs/sso-settings.md
Labels: Kat One

#1437 Kt revamps requirement coverage
  pages/katalon-analytics/docs/requirement-coverage.md
  pages/katalon-analytics/docs/testops-terminology.md
Labels: kt-revamps

#1432 KS-TDAP-274-Add troubleshoot doc for chrome browser in windows - TestOps + KRE
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/troubleshoot-globalvariable-special-character.md
  pages/katalon-testcloud/troubleshoot-chrome-windows.md
Labels: KS, TestCloud

#1318 KS-TDAP-165-Add an issue to troubleshoot common exceptions
  pages/katalon-studio/docs/troubleshoot-common-execution-exceptions-web-test.md
Labels: KS, Large, 8.2.0 release

#1399 KS - TDAP-232 - Update Smart Wait docs
  pages/katalon-studio/docs/webui-smartwait.md
Labels: Extra Small, 8.2.0 release

#1400 KS - TDAP-220 - Update Activate KRE License Screenshot
  pages/katalon-studio/docs/activate-KSE.md
Labels: Extra Small, 8.2.0 release

#1403 KS-TDAP-189-Update 8.2.0 function in [WebUI]Click + Clickoffset
  pages/katalon-studio/docs/webui-click-offset.md
  pages/katalon-studio/docs/webui-click.md
Labels: Extra Small, No Changes, 8.2.0 release

#1405 KS - TDAP-231 - Release Notes 8.2.0
  pages/katalon-studio/new/version-8x.md
Labels: Extra Small, 8.2.0 release

#1408 KS-TDAP-235-Update screenshot for Test Suite Collection
  pages/katalon-studio/docs/test-suite-collection.md
Labels: KS, Extra Small, 8.2.0 release

#1409 KS- TDAP-221-Update new UI for KS preferences
  pages/katalon-studio/docs/katalon-studio-preferences.md
Labels: KS, Small, 8.2.0 release

#1422 KS-TDAP-222-Update screenshot for Project Settings
  pages/katalon-studio/docs/execution-settings.md
  pages/katalon-studio/docs/time-capsule.md
  pages/katalon-studio/docs/webui-smartwait.md
Labels: 8.2.0 release

#1445 KS - TDAP-233 - Update link to What's New in v8.2.0
  pages/katalon-studio/docs/overview.md
Labels: 8.2.0 release

#1447 Update sidebar for KRE troubleshoot doc
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: bug

#1448 Update table form
  pages/katalon-studio/docs/katalon-studio-preferences.md
Labels: bug

#1449 Resolve some comments on 820 release docs
  pages/katalon-analytics/docs/license-idle-timeout.md
  pages/katalon-studio/docs/webui-smartwait.md
  pages/katalon-studio/new/version-8x.md
Labels: 8.2.0 release

#1450 Fix table form
  pages/katalon-studio/docs/test-suite-collection.md
Labels: bug, 8.2.0 release

#1451 Fix table form again
  pages/katalon-studio/docs/test-suite-collection.md
Labels: bug, 8.2.0 release

#1407 KS-TDAP-210-Update-KS-Slack-Integration-docs
  pages/katalon-studio/docs/slack-plugin-integration.md
Labels: Small, ks-revamp

#1438 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: kt-revamps

#1455 TDAP-206: Add modal function + set default image alignment in the center
  _layouts/docs.html
  css/customstyles.scss
  css/image-modal.css
  js/image-modal.js
Labels: enhancement

#1458 Enable to enlarge picture
  pages/katalon-studio/docs/test-suite-collection.md
Labels: enhancement

#1462 Tdap-296-Fix word break in the table
  _layouts/docs.html
  css/customstyles.scss
Labels: enhancement

#1453 KR-TDAP-270-Improve-the-DDT-guide
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-recorder/docs/Get Your Job Done/Data-driven testing/data-driven-execution.md
  pages/katalon-recorder/docs/Get Your Job Done/Data-driven testing/data-driven-testing.md
Labels: KR

#1456 Create view-traceability-matrix.md
  pages/katalon-analytics/docs/view-traceability-matrix.md
Labels: TestOps

#1444 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: TestOps, Kat One

#1436 KT- TDAP-275 Update Admin permission granting rights in the Roles and Privileges page
  pages/katalon-analytics/docs/org-level-roles-privileges.md
Labels: KT, Kat One

#1420 KS- TDAP-253-Installation overview revamp
  pages/katalon-studio/docs/getting-started.md
  pages/katalon-studio/docs/katalon-studio-gui-beta-for-linux.md
  pages/katalon-studio/docs/ks-install-macOS-windows.md
Labels: ks-revamp

#1460 KS-TDAP-264-Change sidebar for KS overhaul - Sprint 5
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: ks-revamp

#1465 KS-TDAP-84-Plugins usage note for KRE
  pages/katalon-studio/docs/kse-use-plugins.md
Labels: KS

#1464 KS-TDAP-99-Create-a-debug-test-case-tutorial-for-web-UI
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/tutorials/webui-analyze-test-case-execution-logs-and-resolve-errors.md
Labels: KS, ks-revamp

#1423 KatOne - TDAP-268 - Allow users to export License Utilization
  pages/katalon-studio/docs/license-utilization-dashboard.md
Labels: Kat One

#1443 Create kt-transfer-ownership.md
  pages/katalon-analytics/docs/kt-create-organization.md
  pages/katalon-analytics/docs/kt-transfer-ownership.md
Labels: Kat One

#1466 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: Kat One
