Repository katalon-studio/docs, pull requests merged in 2021-08, with the labels that each got.

#1196 Update kt-jira-issue.md
  pages/katalon-analytics/docs/kt-jira-issue.md
Labels: Extra Small, kt-revamps

#1227 Edits auto distributed execution
  pages/katalon-analytics/docs/auto-distributed-execution.md
  pages/katalon-studio/docs/selenium-testng-junit-migration.md
Labels: Extra Small

#1233 Licenses Section Revampt
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: Small

#1221 Kt revamps notifications config
  pages/katalon-analytics/docs/kt-noti-email.md
Labels: Extra Small, kt-revamps

#1222 Kt revamps enable strict domain
  pages/katalon-analytics/docs/strict-domain.md
Labels: Extra Small, kt-revamps

#1223 Kt revamps subdomain
  pages/katalon-analytics/docs/subdomain.md
Labels: Extra Small, kt-revamps

#1224 Kt revamps sso settings
  pages/katalon-analytics/docs/accept-sso.md
  pages/katalon-analytics/docs/sso-settings.md
Labels: Medium, kt-revamps

#1231 Update create-plan.md
  pages/katalon-analytics/docs/create-plan.md
Labels: Extra Small, kt-revamps

#1232 Kt revamps update enterprise plan
  pages/katalon-analytics/docs/view-abnormal-web-services.md
  pages/katalon-studio/docs/ks_visual_testing.md
Labels: Extra Small, TestOps

#1238 Kt revamps ip settings
  pages/katalon-analytics/docs/ip-settings.md
Labels: Extra Small, kt-revamps

#1239 Kt revamps delete data
  pages/katalon-analytics/docs/project-management-delete.md
Labels: Small, kt-revamps

#1225 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: Extra Small, kt-revamps

#1236 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: Extra Small, kt-revamps

#1250 Update azure-devops-test-plans.md
  pages/katalon-studio/docs/azure-devops-test-plans.md
Labels: KS, Medium, Release 8.1.0

#1171 [WIP] Release Note 8.1.0
  pages/katalon-studio/new/version-8x.md
Labels: KS, Small, Release 8.1.0

#1247 Create what-is-new-810.md
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/new/what-is-new-810.md
Labels: KS, Small, Release 8.1.0

#1235 Display New Update dialog for chosen version
  pages/katalon-studio/docs/auto-updater.md
Labels: KS, Extra Small, Release 8.1.0

#1234 [Mobile testing] Introduced waitForElementNotPresent
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/mobile-wait-for-element-not-present.md
  pages/katalon-studio/docs/mobile-wait-for-element-present.md
Labels: KS, Medium, Release 8.1.0

#1215 Terminate execution conditionally - tutorial
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/tutorials/condition-to-stop.md
Labels: KS, Small, Release 8.1.0

#1198 Retry Failed Executions Immediately
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/console-mode-execution.md
  pages/katalon-studio/docs/create-test-suite.md
Labels: KS, Small, Release 8.1.0

#1200 Update integrate_with_Kobiton docs and CLI command
  pages/katalon-studio/docs/console-mode-execution.md
  pages/katalon-studio/tutorials/integrate_with_kobiton.md
Labels: KS, Medium, Release 8.1.0

#1251 Separate and move up release notes
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/kte-whats-new-in-july-release.md
Labels: KS, Small

#1240 Kt revamps terminology
  pages/katalon-analytics/docs/testops-terminology.md
Labels: Extra Large, kt-revamps

#1257 Remove 2 retry options
  pages/katalon-studio/docs/console-mode-execution.md
Labels: Extra Small

#1260 Kt to op removal
  pages/katalon-analytics/docs/kt_install_premises_docker.md
  pages/katalon-analytics/docs/testops-april-release-trial-plans.md
  pages/katalon-analytics/docs/testops_subscriptions_overview.md
  pages/katalon-studio/docs/license-server-ubuntu.md
Labels: Small

#1256 Update license-server.md
  pages/katalon-studio/docs/license-server.md
Labels: Large

#1263 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: Extra Small

#1264 Update license-server.md
  pages/katalon-studio/docs/license-server.md
Labels: Extra Small

#1237 Kt revamps junit upload
  pages/katalon-analytics/docs/testops-uploader.md
Labels: Extra Small, kt-revamps

#1245 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: Medium

#1246 Delete view-reports-overview.md
  pages/katalon-analytics/docs/view-reports-overview.md
Labels: Extra Small
