Repository katalon-studio/docs, pull requests merged in 2021-05, with the labels that each got.

#1093 Alttext2
  pages/katalon-analytics/docs/code-repo.md
  pages/katalon-analytics/docs/compare-test-results.md
Labels: Extra Small

#1060 Adding profile details to the email reports
  pages/katalon-studio/docs/execution-settings.md
Labels: KS, Release 8.0.0, Small

#1057 Web UI - Create test case
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/tutorials/webui-create-test-case.md
Labels: Small

#1092 Update introduction-to-desired-capabilities.md
  pages/katalon-studio/docs/introduction-to-desired-capabilities.md
Labels: Extra Small

#1088 Edit-Testops-april-release-subscription-upgrade
  pages/katalon-analytics/docs/testops-april-release-subscription-upgrade.md
Labels: Extra Small

#1095 update url
  pages/katalon-analytics/docs/testops-april-release-subscription-upgrade.md
Labels: Extra Small

#1089 Update testops-april-release-cancel-subscription.md
  pages/katalon-analytics/docs/testops-april-release-cancel-subscription.md
Labels: Extra Small

#1090 Update testops-april-release-trial-plans.md
  pages/katalon-analytics/docs/testops-april-release-trial-plans.md
Labels: Extra Small

#1096 update
  pages/katalon-analytics/docs/testops-april-release-subscription-upgrade.md
Labels: Extra Small

#1091 Update kte-whats-new-in-april-release.md
  pages/katalon-analytics/docs/kte-whats-new-in-april-release.md
Labels: Extra Small

#1098 update
  pages/katalon-analytics/docs/testops-april-release-trial-plans.md
Labels: Extra Small

#1052 Bitbucket Integration
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/bitbucket-intergration.md
  pages/katalon-studio/docs/git-integration.md
Labels: KS, Release 8.0.0, Small

#1066 Import Rest requests with OpenAPI
  pages/katalon-studio/docs/apiweb-service-project-since-v58.md
  pages/katalon-studio/docs/import-openapi30.md
  pages/katalon-studio/docs/import-rest-requests-from-swagger-20.md
  pages/katalon-studio/docs/manage-test-project.md
Labels: KS, Release 8.0.0, Small

#1042 Update Database settings
  pages/katalon-studio/docs/database-settings.md
  pages/katalon-studio/docs/external-libraries.md
  pages/katalon-studio/docs/introduction-to-custom-keywords.md
Labels: KS, Release 8.0.0, Small

#1064 Integration with Azure DevOps Test Plans
  pages/katalon-studio/docs/azure_devops_integration.md
Labels: KS, Medium, Release 8.0.0

#1044 Docs for R8.0
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/azure-devops-extension.md
  pages/katalon-studio/new/version-70.md
  pages/katalon-studio/new/version-8x.md
  pages/katalon-studio/new/what-is-new-79.md
  pages/katalon-studio/new/what-is-new-800.md
Labels: KS, Medium, Release 8.0.0

#1102 updated
  pages/katalon-studio/docs/overview.md
Labels: Extra Small

#1103 updated
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: Extra Small

#1101 Update Testops april release subscription via screen
  pages/katalon-analytics/docs/testops-subscription.md
Labels: Small

#1106 Update MySQL Database Connection
  pages/katalon-studio/how-to-guides/how-to-implement-ddt-mysql.md
Labels: Extra Small, KS, Release 8.0.0

#1107 Update version for new CLIs
  pages/katalon-studio/docs/console-mode-execution.md
Labels: Extra Small, KS, Release 8.0.0

#1108 Create Testops configure timeout session
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/testops-session-timeout.md
Labels: Extra Small

#1111 Update screenshots-videos.md
  pages/katalon-studio/docs/screenshots-videos.md
Labels: Extra Small

#1113 Update ADO Definition ID
  pages/katalon-studio/docs/console-mode-execution.md
Labels: Extra Small

#1121 [KR] Update the edited version of What's new in v5.4
  pages/katalon-recorder/docs/Getting Started/whats-new/whats-new.md
Labels: Extra Small

#1124 Create Testops may dashboard overview
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/dashboard-overview.md
Labels: Extra Small, May, New, TestOps

#1126 Update url
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: Extra Small

#1125 Update testops-releases-2021
  pages/katalon-analytics/docs/testops-releases-2021.md
Labels: Extra Small, May, TestOps
