Repository katalon-studio/docs, pull requests merged in 2021-04, with the labels that each got.

#1051 Getting started
  pages/katalon-analytics/docs/kt-change-result-pass-fail.md
  pages/katalon-analytics/docs/slack-integration.md
Labels: Extra Small

#1053 Add daily usage
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-recorder/docs/Get Your Job Done/Social Values/daily-usage.md
Labels: Extra Small

#1054 Add daily usage
  pages/katalon-recorder/docs/Getting Started/release-notes.md
Labels: Extra Small

#1055 Add daily usage
  pages/katalon-recorder/docs/Getting Started/release-notes.md
Labels: Extra Small

#1045 Azure DevOps Integrations
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/azure_devops_integration.md
Labels: Medium

#1061 Update what's new page for KR
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-recorder/docs/Get Your Job Done/Automate Scenarios/automate-scenarios.md
  pages/katalon-recorder/docs/Get Your Job Done/Social Values/daily-usage.md
  pages/katalon-recorder/docs/Getting Started/whats-new.md
Labels: Extra Small

#1062 Update Automate Scenarios and What's new
  pages/katalon-recorder/docs/Get Your Job Done/Automate Scenarios/automate-scenarios.md
  pages/katalon-recorder/docs/Getting Started/whats-new.md
Labels: Extra Small

#1063 Update URL of what's new page in what's new page
  pages/katalon-recorder/docs/Getting Started/whats-new.md
Labels: Extra Small

#1065 Separate Automate Scenarios into Tutorials, References and Explanations
  pages/katalon-recorder/docs/Get Your Job Done/Automate Scenarios/automate-scenarios.md
Labels: Extra Small

#1041 Update execution-profile-v54.md
  pages/katalon-studio/docs/execution-profile-v54.md
Labels: Small

#1067 Update cucumber-kw-run-feature-folder.md
  pages/katalon-studio/docs/cucumber-kw-run-feature-folder.md
Labels: Extra Small

#1056 Update intro_mobile_app_testing.md
  pages/katalon-studio/videos/intro_mobile_app_testing.md
Labels: Extra Small

#1069 Getting started
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/agents.md
  pages/katalon-analytics/docs/kt-upload-test-pytest.md
  pages/katalon-analytics/docs/kt_kobiton_integration.md
  pages/katalon-analytics/docs/kt_run_parallel_agent.md
Labels: Small

#1058 Update version-70.md
  pages/katalon-studio/new/version-70.md
Labels: Extra Small

#1074 Update TestOps release notes
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/advanced-0.1.x.md
  pages/katalon-analytics/docs/kt-april.md
  pages/katalon-analytics/docs/overwrite-test-run.md
  pages/katalon-analytics/docs/testops-releases.md
Labels: April, Small

#1081 update
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/testops-releases-2021.md
Labels: Extra Small

#1073 Create kte-whats-new-in-testops-1.md
  pages/katalon-analytics/docs/kte-whats-new-in-april-release.md
Labels: April, Extra Small

#1083 update sidebar
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/testops-releases-2021.md
Labels: Extra Small

#1084 update url
  pages/katalon-analytics/docs/testops-releases-2021.md
Labels: Extra Small

#1085 update
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: Extra Small

#1076 Create testops-april-release-subscription-via-screen.md
  pages/katalon-analytics/docs/testops-subscription.md
Labels: April, Extra Small

#1087 update Create subs
  pages/katalon-analytics/docs/testops-subscription.md
Labels: Extra Small

#1077 Create testops-april-release-subscription-upgrade.md
  pages/katalon-analytics/docs/testops-april-release-subscription-upgrade.md
Labels: April, Extra Small

#1078 Create testops-april-release-cancel-subscription.md
  pages/katalon-analytics/docs/testops-april-release-cancel-subscription.md
Labels: April, Extra Small

#1086 Getting started
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-analytics/docs/kt_install_premises_docker.md
  pages/katalon-analytics/docs/testops_subscriptions_overview.md
Labels: Small
