Repository katalon-studio/docs, pull requests merged in 2022-01, with the labels that each got.

#1532 TDAP-355-Revamp sidebar sprint 8
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: ks-revamp

#1531 KR-344-Create-a-tutorial-for-extracting-and-verifying-textual-patterns
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-recorder/docs/Get Your Job Done/Automate Scenarios/how-to-extract-and-verify-textual-patterns-in-a-test-case.md
Labels: KR

#1505 TDAP-317 Update UI and restructure the Self-healing tests document
  pages/katalon-studio/docs/self-healing.md
  pages/katalon-studio/docs/web-selection-methods.md
Labels: ks-revamp

#1541 KS-TDAP-256+337-Revamp & Update supported environment doc
  pages/katalon-studio/docs/supported-environments.md
Labels: KS

#1524 TDAP-330 Instruction to activate KRE - offline floating license
  pages/katalon-studio/docs/license-server.md
Labels: license-revamp

#1306 KS-TDAP-171-PoC-DDT at test case level
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/ddt-at-test-case-level.md
Labels: KS, Medium

#1513 TDAP-324 [KS 8.2.5] Release Notes
  pages/katalon-studio/new/version-8x.md
Labels: 8.2.5 release

#1530 KS-TDAP-95+353-Update timestamp + screenshot for project settings
  pages/katalon-studio/docs/desired-capabilities-at-runtime.md
  pages/katalon-studio/docs/desired-capabilities-custom-settings.md
  pages/katalon-studio/docs/desired-capabilities-remote-settings.md
  pages/katalon-studio/docs/desired-capabilities-settings-webui.md
  pages/katalon-studio/docs/desired-capabilities-settings-windows.md
  pages/katalon-studio/docs/execution-settings.md
  pages/katalon-studio/docs/how-to-test-different-locales-with-desired-capabilities.md
  pages/katalon-studio/docs/import-export-desired-capabilities.md
  pages/katalon-studio/docs/selenium-grid-integration.md
  pages/katalon-studio/docs/setup-winappdriver.md
  pages/katalon-studio/docs/start-browsers-in-private-mode.md
  pages/katalon-studio/docs/time-capsule.md
  pages/katalon-studio/docs/webui-smartwait.md
Labels: 8.2.5 release

#1533 KS-TDAP-302-Update UI changes in license documents
  pages/katalon-studio/docs/activate-KSE.md
  pages/katalon-studio/docs/configure-proxy.md
  pages/katalon-studio/docs/license-idle-timeout.md
  pages/katalon-studio/docs/machine-id.md
  pages/katalon-studio/docs/troubleshoot-activation-problems.md
Labels: 8.2.5 release

#1535 KS-TDAP-334 Update + revamp qtest integration doc
  pages/katalon-studio/docs/qtest-integration.md
Labels: 8.2.5 release

#1536 KS-TDAP-331-Update TestOps integration doc
  pages/katalon-analytics/docs/create-plan.md
  pages/katalon-studio/docs/katalon-analytics-beta-integration.md
Labels: 8.2.5 release

#1537 KS-TDAP-363 Update UI change in the toolbar
  pages/katalon-studio/docs/android-sample-prj.md
  pages/katalon-studio/docs/configure-android-studio.md
  pages/katalon-studio/docs/health-care-prj.md
  pages/katalon-studio/docs/ios-sample-prj.md
  pages/katalon-studio/docs/shopping-cart-prj.md
  pages/katalon-studio/docs/toolbars-and-views.md
  pages/katalon-studio/tutorials/mobile-android-setup.md
  pages/katalon-studio/tutorials/mobile-create-android-test-case.md
  pages/katalon-studio/tutorials/mobile-create-ios-test-case.md
  pages/katalon-studio/tutorials/mobile-ios-setup.md
  pages/katalon-studio/tutorials/webui-create-test-case.md
Labels: 8.2.5 release

#1540 Ks tdap 325 test cloud integration docs
  pages/katalon-studio/docs/testcloud-integration-kre.md
  pages/katalon-studio/docs/testcloud-integration.md
Labels: 8.2.5 release

#1543 TDAP-365 [KS 8.2.5] Add TestCloud Integration command-line options in the Command Syntax document
  pages/katalon-studio/docs/console-mode-execution.md
Labels: 8.2.5 release

#1545 TDAP-364 [KS 8.2.5] Update UI changes in the toolbars-related doc (Part 2)
  pages/katalon-studio/docs/Introduction-desktop-app-testing.md
  pages/katalon-studio/docs/mobile-recorder-tutorials.md
  pages/katalon-studio/docs/windows-native-record.md
  pages/katalon-studio/docs/windows_recorder_tutorials.md
  pages/katalon-studio/tutorials/running_application_mobile_browsers.md
Labels: 8.2.5 release

#1546 KS-TDAP-357-Revamp update UI dynamic test suite
  pages/katalon-studio/docs/create-test-suite.md
  pages/katalon-studio/docs/dynamic-test-suite-ks.md
Labels: 8.2.5 release

#1548 TDAP-366 [KS 8.2.5] Working with Web Locators Strategies (Xpath and Attributes)
  pages/katalon-studio/docs/web-selection-methods.md
Labels: 8.2.5 release

#1551 KS-TDAP-356-Update screenshot test cloud project settings-PART2
  pages/katalon-studio/docs/aws-device-farm-integration.md
  pages/katalon-studio/docs/browserstack-integration.md
  pages/katalon-studio/docs/database-settings.md
  pages/katalon-studio/docs/execute-a-test-case-or-a-test-suite.md
  pages/katalon-studio/docs/external-libraries.md
  pages/katalon-studio/docs/headless-browsers-execution.md
  pages/katalon-studio/docs/how-to-capture-objects-in-hybrid-apps.md
  pages/katalon-studio/docs/jenkins-pipeline-docker.md
  pages/katalon-studio/docs/jira-integration.md
  pages/katalon-studio/docs/lambdatest-integration.md
  pages/katalon-studio/docs/rally-integration.md
  pages/katalon-studio/docs/restful.md
  pages/katalon-studio/docs/saucelabs-plugin.md
  pages/katalon-studio/docs/screenshots-videos.md
  pages/katalon-studio/docs/test-suite-report.md
  pages/katalon-studio/docs/testlink-integration.md
  pages/katalon-studio/docs/testrail-integration.md
  pages/katalon-studio/how-to-guides/how-to-implement-ddt-mysql.md
  pages/katalon-studio/tutorials/create_first_api_test_katalon_studio.md
  pages/katalon-studio/tutorials/flutter-based-application-testing.md
Labels: 8.2.5 release

#1552 KS-TDAP-284-Update search doc
  pages/katalon-studio/docs/search.md
Labels: 8.2.5 release

#1555 TDAP-378 [KS 8.2.5] Update Known Limitation for KCU document
  pages/katalon-studio/docs/katalon-compact-utility.md
Labels: 8.2.5 release

#1561 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: 8.2.5 release

#1562 TDAP-361-Update windows 11
  pages/katalon-studio/docs/supported-environments.md
Labels: 8.2.5 release

#1534 TC-TDAP-346-Update-documents-related-to-GA-Trial
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-testcloud/testcloud-overview.md
Labels: TestCloud

#1550 TC-TDAP-380-Create-an-entry-for-TestCloud-on-the-welcome-document
  pages/katalon-studio/docs/index.md
Labels: TestCloud

#1544 KS-TDAP-294-Revamp-documents-related-to-running-feature-files-with-tags
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/cucumber-kw-run-feature-file-tag.md
  pages/katalon-studio/docs/cucumber-kw-run-feature-folder-tag.md
Labels: KS

#1553 Update git-test-project.md
  pages/katalon-analytics/docs/git-test-project.md
Labels: TestOps

#1557 Create create-test-suite.md
  pages/katalon-analytics/docs/create-test-suite.md
  pages/katalon-analytics/docs/test-case-management-journey.md
Labels: TestOps

#1558 Update create-plan.md
  pages/katalon-analytics/docs/create-plan.md
Labels: TestOps

#1564 Create testops-releases-2022.md
  pages/katalon-analytics/docs/testops-releases-2022.md
Labels: TestOps

#1565 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: TestOps, TestCloud

#1547 KS-TDAP-376-Revamp-the-windows-desktop-apps-documents-part1
  _data/sidebars/katalon_studio_docs_sidebar.yml
  pages/katalon-studio/docs/intro-record-windows.md
  pages/katalon-studio/docs/intro-spy-windows.md
  pages/katalon-studio/docs/windows-spy-tutorials.md
Labels: ks-revamp

#1563 TC-TDAP-394-Create-Release-notes-for-TestCloud-trial-period
  pages/katalon-testcloud/release-notes.md
Labels: TestCloud

#1538 Create testcloud-tunnel.md
  pages/katalon-testcloud/integrate-testcloud-with-testops.md
  pages/katalon-testcloud/testcloud-tunnel.md
Labels: TestCloud

#1568 KS-TDAP-388-Update-the-KS-KSE-feature-comparison
  pages/katalon-studio/docs/ks-vs-kse.md
Labels: ks-revamp

#1567 KS-TDAP-297-Revamp sample project-PART3
  pages/katalon-studio/docs/bdd-samples.md
  pages/katalon-studio/docs/web-service-samples.md
Labels: ks-revamp

#1576 KS-TDAP-367-Create a hybrid app testing overview + Add requirements & correct redirect links for Dynamic Test Suite
  pages/katalon-studio/docs/create-test-suite.md
  pages/katalon-studio/docs/dynamic-test-suite-ks.md
  pages/katalon-studio/docs/hybrid-app-overview.md
Labels: ks-revamp

#1575 KS-TDAP-375-Change Dynamic Test Suite URL
  pages/katalon-studio/docs/basic-search-for-dynamic-querying-test-suite.md
  pages/katalon-studio/docs/ddt-at-test-case-level.md
Labels: ks-revamp

#1581 Fix broken links and syntax errors
  pages/katalon-analytics/docs/create-test-suite.md
  pages/katalon-analytics/docs/testops-releases-2022.md
  pages/katalon-studio/docs/testcloud-integration-kre.md
Labels: KS, TestOps

#1578 KS-TDAP-421-8.3.0 beta release note
  pages/katalon-studio/new/version-8x.md
Labels: 8.3.0 beta release

#1573 KR-TDAP-415-Create-release-notes-for-KR-5.7.0
  pages/katalon-recorder/docs/Getting Started/release-notes.md
Labels: KR

#1580 KS-TDAP-423-Create dynamic test suite at runtime with kre
  pages/katalon-studio/docs/console-mode-execution.md
  pages/katalon-studio/docs/dynamic-test-suite-kre.md
Labels: KS

#1579 Create testcloud-supported-environments.md
  pages/katalon-testcloud/testcloud-supported-environments.md
Labels: TestCloud

#1582 Tc tdap 427 troubleshoot doc
  pages/katalon-studio/docs/testcloud-integration.md
  pages/katalon-testcloud/integrate-testcloud-with-testops.md
  pages/katalon-testcloud/troubleshoot-macos-workaround.md
Labels: TestCloud

#1577 TDAP-390 [Community] Update video section in doc page
  _data/sidebars/katalon_studio_videos_sidebar.yml
  pages/katalon-studio/videos/asana_api.md
  pages/katalon-studio/videos/configure_authorization.md
  pages/katalon-studio/videos/delete_request.md
  pages/katalon-studio/videos/execution_profile.md
  pages/katalon-studio/videos/install_macos.md
  pages/katalon-studio/videos/install_window.md
  pages/katalon-studio/videos/introduction_download.md
  pages/katalon-studio/videos/request_post.md
  pages/katalon-studio/videos/request_restapi.md
  pages/katalon-studio/videos/request_restapi_put.md
  pages/katalon-studio/videos/request_soap.md
  pages/katalon-studio/videos/types_variables.md
Labels: community

#1584 Update katalon_studio_docs_sidebar.yml
  _data/sidebars/katalon_studio_docs_sidebar.yml
Labels: TestCloud
